import type { Tool, McpServer } from "../../core/index.ts";
import { toJsonSchema } from "../../core/index.ts";
import type { EmittedFile } from "../../core/adapter.ts";

export interface MaterializeOptions {
  /** Id/name for the generated MCP server. */
  serverId?: string;
  /**
   * Module specifier the generated server imports to get the live handlers.
   * It must export `tools` — the same array of `Tool` objects. Typically the
   * entry file that defines the backpack.
   */
  toolsModule: string;
  /** Path for the generated server file. Defaults to `.backpack/mcp/<id>.ts`. */
  serverFilePath?: string;
}

export interface MaterializedTools {
  server: McpServer;
  file: EmittedFile;
}

interface ToolDef {
  name: string;
  description: string;
  inputSchema: unknown;
}

/**
 * Bundle every `Tool` into one generated stdio MCP server so any CLI can consume
 * them without the user hand-writing MCP config. Tool metadata (name/description/
 * JSON-Schema) is inlined at emit time; the live `handler`s are imported from
 * `toolsModule` at runtime and matched by id.
 */
export function materializeTools(
  tools: Tool[],
  opts: MaterializeOptions,
): MaterializedTools {
  const serverId = opts.serverId ?? "backpack-tools";
  const serverFilePath = opts.serverFilePath ?? `.backpack/mcp/${serverId}.ts`;

  const defs: ToolDef[] = tools.map((tool) => ({
    name: tool.id,
    description: tool.description,
    inputSchema: toJsonSchema(tool.parameters),
  }));

  const file: EmittedFile = {
    path: serverFilePath,
    scope: "project",
    content: renderServer(defs, opts.toolsModule),
  };

  const server: McpServer = {
    id: serverId,
    name: serverId,
    description: "Backpack-generated MCP server hosting custom tools",
    enabled: true,
    connection: {
      type: "stdio",
      command: "bun",
      args: [serverFilePath],
    },
  };

  return { server, file };
}

/** Renders a self-contained (dependency-free) MCP stdio server. */
function renderServer(defs: ToolDef[], toolsModule: string): string {
  return `// Generated by backpack. Do not edit by hand.
// Minimal MCP stdio server (JSON-RPC 2.0, newline-delimited) hosting custom tools.
import { tools } from ${JSON.stringify(toolsModule)};

const DEFS = ${JSON.stringify(defs, null, 2)} as const;
const handlers = new Map(tools.map((t) => [t.id, t.handler]));

function normalize(result) {
  if (typeof result === "string") {
    return { content: [{ type: "text", text: result }] };
  }
  return result;
}

async function handle(msg) {
  const { id, method, params } = msg;
  switch (method) {
    case "initialize":
      return {
        jsonrpc: "2.0",
        id,
        result: {
          protocolVersion: "2024-11-05",
          capabilities: { tools: {} },
          serverInfo: { name: "backpack-tools", version: "0.1.0" },
        },
      };
    case "tools/list":
      return { jsonrpc: "2.0", id, result: { tools: DEFS } };
    case "tools/call": {
      const handler = handlers.get(params?.name);
      if (!handler) {
        return {
          jsonrpc: "2.0",
          id,
          error: { code: -32602, message: \`Unknown tool: \${params?.name}\` },
        };
      }
      try {
        const out = normalize(await handler(params?.arguments ?? {}));
        return { jsonrpc: "2.0", id, result: out };
      } catch (err) {
        return {
          jsonrpc: "2.0",
          id,
          result: {
            content: [{ type: "text", text: String(err) }],
            isError: true,
          },
        };
      }
    }
    default:
      // Notifications (no id) get no response.
      if (id === undefined) return null;
      return {
        jsonrpc: "2.0",
        id,
        error: { code: -32601, message: \`Method not found: \${method}\` },
      };
  }
}

const decoder = new TextDecoder();
let buffer = "";
for await (const chunk of Bun.stdin.stream()) {
  buffer += decoder.decode(chunk);
  let idx;
  while ((idx = buffer.indexOf("\\n")) !== -1) {
    const line = buffer.slice(0, idx).trim();
    buffer = buffer.slice(idx + 1);
    if (!line) continue;
    const response = await handle(JSON.parse(line));
    if (response) process.stdout.write(JSON.stringify(response) + "\\n");
  }
}
`;
}
